# Site settings
title: '대가가 되고자 하는 꿈을 꾼다.'
description: '무엇인가 되고자 하기 위해 한걸음 두걸음'
url: "https://kdreamtomaster.github.io"
baseurl: ""
github_username: Kdreamtomaster
author: 강신우
email: kang.shin.woo.23@gmail.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lunr-js-search

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Navigation menu
header_pages:
  - index.md
  - posts.md
  - achievements.md
  - tools.md
  - about.md

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:name/
  tools:
    output: true
    permalink: /tools/:name/
  series:
    output: true
    permalink: /series/:name/
  achievements:
    output: true
    permalink: /achievements/:name/

# Category structure
category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - java
      - web-automation
  data_science:
    title: Data Engineering
    subcategories:
      - data_preprocessing
      - data_engineering_architecture
      - mlops
      - data_platform
  devops_and_cloud:
    title: DevOps & Cloud
    subcategories:
      - ci_cd
      - containerization
      - cloud_services

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_achievements"
    values:
      layout: "achievement"

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# SEO related


social:
  name: 강신우
  links:
    - https://github.com/Kdreamtomaster


